<?php

//error codes

const REQUEST_FAILED_VALIDATION_CODE = 100;
const MODEL_NOT_FOUND_CODE = 102;
const UNEXPLAINED_ERROR_CODE = 107;
const NO_TRANSACTION_TOKEN_FOUND_IN_HEADER_CODE = 112;
const TRANSACTION_TOKEN_HAS_EXPIRED_CODE = 113;
const INSUFFICIENT_WALLET_BALANCE_CODE = 116;
const SENDING_PAYMENT_TO_SELF_UNSUPPORTED_CODE = 141;
const QUERY_PARAM_NOT_FOUND_IN_URL_CODE = 154;

const BAD_REQUEST_CODE = 163;
const TIMEOUT_CODE = 164;

const THETELLER_ACCESS_DENIED_CODE = 168;

// OTP err codes



const OTP_EXPIRES_IN = 6000;


const KYC_ID_VERIFICATION_FAILED_CODE = 721;

const BRAAS_FAILED_VALIDATION = '1004';
const BRAAS_TRANSACTION_PENDING = '1006';
const BRAAS_TRANSACTION_FAILED = '1007';

const BRAAS_TRANSACTION_UNAVAILABLE = '1010';


const TOKEN_EXPIRATION_IN_HOURS = 5;


//PAYOUT STATUS CODES
const SUCCESSFUL_PAYOUT_STATUS_CODE = '000';
const PENDING_PAYOUT_STATUS_CODE = '001';
const FAILED_PAYOUT_STATUS_CODE = '002';

const HTTP_UNPROCESSED_STATUS_ENTITY_CODE = 422;
const HTTP_SUCCESSFUL_STATUS_CODE = 200;




